---
title: "Data Science HW 2"
author: Hingling Yu
date: 10/01/2023
output: github_document
geometry: margin=0.85in
fontsize: 12pt
  
---

## Problem 0

```{r load_libraries}
library(tidyverse)
library(readxl)
library(lubridate)
```

## Problem 1

### First Step: Cleaning `pols-month.csv`

```{r clean_538_pols}
pols = 
  read_csv("data/data_fivethirtyeight/pols-month.csv") %>% #import the `pols-month.csv` file
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% # split the mon column into three columns: year, month, day using "="
  mutate(
    month = month.name[as.numeric(month)], # converts numeric month values to full month names
    president = ifelse(prez_gop == 1, "gop", "dem"), # creates a new variable president, assign 'gop' if prez_gop = 1, otherwise assign 'dem'
    year = as.numeric(year)
  ) %>% 
  select(year, month, everything(), -day, -starts_with("prez")) # select all variables except 'day' and everything starts with 'prez'
```



### Second Step: Cleaning `snp.csv`
```{r clean_538_snp}
snp = 
  read_csv("data/data_fivethirtyeight/snp.csv") %>% #import the `snp.csv` file
  separate(date, into = c("month", "day", "year"), sep = "/") %>% # split the data column into three columns: month, day, year using "/"
  mutate(
    month = month.name[as.numeric(month)], 
    year = as.numeric(year),
    year = ifelse(year < 50, year + 2000, year + 1900) # add 2000 to years value less than 50, 1900 to years value greater or equal to 50
  ) %>% #converts numeric month to full month names
  select(year, month, close, -day) # rearrange the columns so "year" and "month" at first, then "close". Remove "day"


```


### Third Step: Tidy `umeployment.csv`
```{r clean_538_unemployment}
unemployment = 
  read_csv("data/data_fivethirtyeight/unemployment.csv") %>%  #import the `unemployment.csv`
  rename(year = Year) %>% # rename 'Year' column to 'year'
  pivot_longer(
    Jan:Dec, # convert from wide to long
    names_to = "month", # names of the columns into a new column named 'month'
    values_to = "unemployment_rate"# values of the columns into a new column named 'unemployment_rate'
    ) %>% 
  mutate(
    month = month.name[match(month, month.abb)],
    year = as.numeric(year)
    ) %>% # finds the position of each month abbreviation name in month.abb vector then concert these month abbreviation names to full month names
  select(year, month, unemployment_rate) 

```


### Last Step: Merge three datasets


```{r merge_538}
data_538 =
  left_join(pols, snp) %>% 
  left_join(unemployment)
```

